Crud functionality for users
FriendsRecCollaborative/FriendsRec pull request #12
Opened 2023-08-29 02:51 UTC by wnguye03

## Overview

**Issue Type**

- [ ] Bug
- [x] Feature
- [ ] Tech Debt

**Description**
- Implemented users CRUD functionality for creating new users, and the networking features outlined in the ticket, removing friends, adding friends, getting users, and getting a specific user (for searching for friends).

**Ticket Item**
- express basic crud functionality for users

2023-08-29 03:03 UTC, larkinaj approved these changes
Approved

2023-08-29 22:13 UTC, YouruiR commented
I am receiving errors when trying to login and register
<img width="860" alt="Screenshot 2023-08-29 at 6 13 03 PM" src="https://github.com/FriendsRecCollaborative/FriendsRec/assets/118780080/a661f6f6-1961-4e7f-af84-25fe3ab1706b">

2023-08-29 22:14 UTC, YouruiR requested changes
See comment with screenshot of error

2023-08-30 01:29 UTC, YouruiR approved these changes

2023-08-30 01:29 UTC, merged